<a href="https://colab.research.google.com/github/Dineshkumar013/Bircoin-Prediction/blob/main/Bitcoin_prediction_using_svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
import pandas as pd


In [ ]:
#Store the data into the variable df
df = pd.read_csv('Bitcoin_dataset_updated.csv')
df.head(7)

Date  ...  M2(Not seasonally adjusted)[1e+09 USD]
0  2014-01-02  ...                                 11089.3
1  2014-01-03  ...                                 11089.3
2  2014-01-04  ...                                 11089.3
3  2014-01-05  ...                                 11089.3
4  2014-01-06  ...                                 11089.3
5  2014-01-07  ...                                 11089.3
6  2014-01-08  ...                                 11089.3

[7 rows x 9 columns]

In [ ]:
#Remove the Date column
df.drop(['Date'], 1, inplace=True)


In [ ]:
df=df.drop(['n-transactions','btc search trends','fee [USD]','Gold price[USD]','SP500 close index','Oil WTI price[USD]','M2(Not seasonally adjusted)[1e+09 USD]'],axis=1)

In [ ]:
df.dropna()

BTC price [USD]
0              749.27
1              781.23
2              807.39
3              828.74
4              904.98
...               ...
2305          7507.08
2306          7549.52
2307          7699.27
2308          7790.66
2309          7765.33

[2310 rows x 1 columns]

In [ ]:
#A variable for predicting 'n' days out into the future
prediction_days = 30 #n = 30 days

#Create another column (the target or dependent variable) shifted 'n' units up
df['Prediction'] = df[['BTC price [USD]']].shift(-prediction_days)

In [ ]:
#Show the first 7 rows of the new data set
df

BTC price [USD]  Prediction
0              749.27      803.00
1              781.23      817.08
2              807.39      814.34
3              828.74      808.50
4              904.98      802.99
...               ...         ...
2305          7507.08         NaN
2306          7549.52         NaN
2307          7699.27         NaN
2308          7790.66         NaN
2309          7765.33         NaN

[2310 rows x 2 columns]

In [ ]:
#CREATE THE INDEPENDENT DATA SET (X)

# Convert the dataframe to a numpy array and drop the prediction column
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows where 'n' is the prediction_days
X= X[:len(df)-prediction_days]
#X=pd.Dataframe(X)
print(X)

[[ 749.27]
 [ 781.23]
 [ 807.39]
 ...
 [6369.09]
 [6260.95]
 [5885.41]]


In [ ]:
#CREATE THE DEPENDENT DATA SET (y) 
# Convert the dataframe to a numpy array (All of the values including the NaN's)
y = np.array(df['Prediction'])  
# Get all of the y values except the last 'n' rows 
y = y[:-prediction_days] 
print(y)

[ 803.    817.08  814.34 ... 7699.27 7790.66 7765.33]


In [ ]:
# Split the data into 80% training and 20% testing
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [ ]:
# Set prediction_days_array equal to the last 30 rows of the original data set from the price column
prediction_days_array = np.array(df.drop(['Prediction'],1))[-prediction_days:]
print(prediction_days_array)

[[6405.29]
 [6428.28]
 [6652.87]
 [6809.11]
 [6741.67]
 [6871.69]
 [6777.44]
 [7343.2 ]
 [7205.55]
 [7365.03]
 [7293.69]
 [6873.24]
 [6891.6 ]
 [6915.37]
 [6857.66]
 [6871.95]
 [6623.8 ]
 [7112.27]
 [7034.89]
 [7259.36]
 [7130.04]
 [6840.24]
 [6852.52]
 [7130.99]
 [7477.6 ]
 [7507.08]
 [7549.52]
 [7699.27]
 [7790.66]
 [7765.33]]


In [ ]:
from sklearn.svm import SVR 
# Create and train the Support Vector Machine 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)#Create the model
svr_rbf.fit(x_train, y_train) #Train the model

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=1e-05,
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [ ]:
# Testing Model: Score returns the accuracy of the prediction. 
# The best possible score is 1.0
svr_rbf_confidence = svr_rbf.score(x_test, y_test)
print("svr_rbf accuracy: ", svr_rbf_confidence)

svr_rbf accuracy:  0.8669151347659174


In [ ]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[ 5751.90496265  8588.14659669  4419.82644489  7042.88644136
  8519.68891557  6226.00019007  4134.07204674  8835.26268681
  7997.12216912   874.40660474  8335.52198893   624.17398374
   240.27027518   612.58435799  3943.9583497   8226.55765235
   247.58533362   246.74076178  1440.70485972   648.33929054
  8748.30395239   328.78677212   257.90584151   538.78042465
  6185.03556432  7137.55218861  8343.70296609  8760.15368534
   479.74420036  3938.73081593  8748.82303936   357.7203069
   586.03757945  9896.11741529  7854.29642936  1737.83740423
  8582.25633918   622.1893037   7750.67968626  8896.31175026
  8180.4580882    696.7116205    269.57049609   517.14125897
   903.30605208   590.88183259  8053.01767119   236.9602979
  4051.48388884   569.33514857  3884.64641538   431.10155736
   454.35113752  4052.77945485  7536.56270354  6300.34251643
   444.15438144  1012.28664528   893.38343272   540.71927128
  8046.79351537  8831.55873208   245.13038231   239.71024138
   435.39473873  3910.3295

In [ ]:
# Print the predicted value
svm_prediction = svr_rbf.predict(x_test)
print(svm_prediction)

print()

#Print the actual values
print(y_test)

[ 5751.90496265  8588.14659669  4419.82644489  7042.88644136
  8519.68891557  6226.00019007  4134.07204674  8835.26268681
  7997.12216912   874.40660474  8335.52198893   624.17398374
   240.27027518   612.58435799  3943.9583497   8226.55765235
   247.58533362   246.74076178  1440.70485972   648.33929054
  8748.30395239   328.78677212   257.90584151   538.78042465
  6185.03556432  7137.55218861  8343.70296609  8760.15368534
   479.74420036  3938.73081593  8748.82303936   357.7203069
   586.03757945  9896.11741529  7854.29642936  1737.83740423
  8582.25633918   622.1893037   7750.67968626  8896.31175026
  8180.4580882    696.7116205    269.57049609   517.14125897
   903.30605208   590.88183259  8053.01767119   236.9602979
  4051.48388884   569.33514857  3884.64641538   431.10155736
   454.35113752  4052.77945485  7536.56270354  6300.34251643
   444.15438144  1012.28664528   893.38343272   540.71927128
  8046.79351537  8831.55873208   245.13038231   239.71024138
   435.39473873  3910.3295

In [ ]:
#Print the actual price for the next 'n' days, n=prediction_days=30 
df.tail(prediction_days)

BTC price [USD]  Prediction
2280          6405.29         NaN
2281          6428.28         NaN
2282          6652.87         NaN
2283          6809.11         NaN
2284          6741.67         NaN
2285          6871.69         NaN
2286          6777.44         NaN
2287          7343.20         NaN
2288          7205.55         NaN
2289          7365.03         NaN
2290          7293.69         NaN
2291          6873.24         NaN
2292          6891.60         NaN
2293          6915.37         NaN
2294          6857.66         NaN
2295          6871.95         NaN
2296          6623.80         NaN
2297          7112.27         NaN
2298          7034.89         NaN
2299          7259.36         NaN
2300          7130.04         NaN
2301          6840.24         NaN
2302          6852.52         NaN
2303          7130.99         NaN
2304          7477.60         NaN
2305          7507.08         NaN
2306          7549.52         NaN
2307          7699.27         NaN
2308          7790.66         NaN
2309          7765.33         NaN